// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	listener "github.com/egnd/go-tghandlers/pkg/listener"
	mock "github.com/stretchr/testify/mock"
)

// ChainWrapper is an autogenerated mock type for the ChainWrapper type
type ChainWrapper struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ChainWrapper) Execute(_a0 []listener.EventHandlerDecorator, _a1 listener.ChainWrapper) listener.EventHandler {
	ret := _m.Called(_a0, _a1)

	var r0 listener.EventHandler
	if rf, ok := ret.Get(0).(func([]listener.EventHandlerDecorator, listener.ChainWrapper) listener.EventHandler); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(listener.EventHandler)
		}
	}

	return r0
}
