// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	listener "github.com/egnd/go-tghandlers/pkg/listener"
	mock "github.com/stretchr/testify/mock"
)

// EventHandlerDecorator is an autogenerated mock type for the EventHandlerDecorator type
type EventHandlerDecorator struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *EventHandlerDecorator) Execute(_a0 listener.EventHandler) listener.EventHandler {
	ret := _m.Called(_a0)

	var r0 listener.EventHandler
	if rf, ok := ret.Get(0).(func(listener.EventHandler) listener.EventHandler); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(listener.EventHandler)
		}
	}

	return r0
}
