// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	listener "github.com/egnd/go-tghandlers/pkg/listener"
	mock "github.com/stretchr/testify/mock"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
)

// EventHandler is an autogenerated mock type for the EventHandler type
type EventHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2
func (_m *EventHandler) Execute(_a0 context.Context, _a1 tgbotapi.Update, _a2 listener.ILogger) {
	_m.Called(_a0, _a1, _a2)
}
